on:
  push:
    branches:
      - main 
      - feature/*
      - fix/*
      
jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
        - name: Placeholder for build
          run: echo "This stage will set up python and install dependencies that will be cached across all jobs"
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [build]
    env:
      PYTHON_VER: "3.10"
      POETRY_VER: "1.4.0"
    
    steps:
        - uses: actions/checkout@v3
        - name: Set up ${{ env.PYTHON_VER }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ env.PYTHON_VER }}
            
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
          
        - name: Install poetry
          run: |
            python -m pip install --upgrade pip
            pip install "poetry==${{ env.POETRY_VER }}"
        
        - name: Install dependencies
          run: |
            poetry install
            
        - name: Run lint
          run: |
            poetry run make lint

  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    needs: [lint]
    
    steps:
        - name: Placeholder for unit test
          run: echo "placeholder for unit test"

  integration-test:
    name: integration-test
    runs-on: ubuntu-latest
    needs: [unit-test]
    
    steps:
        - name: Placeholder for integration test
          run: echo "placeholder for integration test"
